spring:
  application:
    name: Kpaas
  datasource:
    url: jdbc:mysql://dev-mysql-project-lb-16f8e-25566320-f3143ebb59b2.kr.lb.naverncp.com:4002/community
    username: root
    password: tndtlfthvmxm1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
